allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  prisma: true
minimumReleaseAgeExclude:
  - diff@4.0.4
  - qs@6.14.2
  - qs@6.14.1
  - file-type@21.3.1
  - file-type@21.3.2
  - '@hono/node-server@1.19.13'
  - ws@8.20.1
  - qs@6.15.2
  - hono@4.12.21
  - ws@8.21.0
  - form-data@4.0.6
  - '@babel/core@7.29.1'
  - hono@4.12.25
  - multer@2.2.0
  - piscina@4.9.3
  - js-yaml@3.15.0
  - js-yaml@4.1.2
